<a href="https://colab.research.google.com/github/ernesto-sadeghi/ai/blob/main/hellow-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing numpy

In [ ]:
import numpy as np


creating random 3x3 array

In [ ]:
random_array = np.random.randint(1,101,size=(3,3))
print(random_array)

[[86  5 56]
 [95 97  4]
 [96 43 46]]


finding max and min

In [ ]:
print("max:",np.max(random_array))
print("min:",np.min(random_array))
#print(np.min(random_array,axis=0)) # min along each column
#print(np.min(random_array,axis=1)) # min along each row

max: 97
min: 4


product of each column

In [ ]:
column_product= np.prod(random_array,axis=0)
print(column_product)

[784320  20855  10304]


In [ ]:
mean = np.mean(random_array)
deviation = np.std(random_array)
print(mean)
print(deviation)

normalized_array = (random_array-mean)/deviation
print(normalized_array)

58.666666666666664
35.29557731186413
[[ 0.77441242 -1.52049267 -0.07555243]
 [ 1.02940187  1.08606619 -1.54882483]
 [ 1.05773403 -0.44387053 -0.35887405]]


**2. reshaping an array**

In [ ]:
javad= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(javad)

threeXfour = javad.reshape(3,4)
print("\n",threeXfour,"\n") #3row 4columns

fourXthree = javad.reshape(4,3)
print(fourXthree) #3row 4columns

[ 1  2  3  4  5  6  7  8  9 10 11 12]

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


multiplying 1x3 with 3x4

In [ ]:
oneXthree = np.array([[1],[2],[3]])
#print(oneXthree)
#print(threeXfour)

print(threeXfour * oneXthree)

[[1]
 [2]
 [3]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


adding 1x4 to 3x4

In [ ]:
oneXfour = np.array([[1,2,3,4]])

print(threeXfour + oneXfour)

[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


**3. Indexing and slicing**

In [ ]:
# arr5x5 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]) # wrong way
arr5x5 = np.arange(1,26).reshape(5,5) # better way
print(arr5x5)
print("")

sub3x3arr = arr5x5[1:4,1:4]
print(sub3x3arr)
print("")

secondRow = arr5x5[1:2]
print(secondRow)
print("")

everyOddIndexColumn = arr5x5[0:6,0:6:2]
print(everyOddIndexColumn)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

[[ 6  7  8  9 10]]

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


extracting element greater than mean

In [ ]:
greaterThanMean = arr5x5[arr5x5 > np.mean(arr5x5)]
print(np.mean(arr5x5))
print(greaterThanMean)

13.0
[14 15 16 17 18 19 20 21 22 23 24 25]


4.linear Algebra opration

In [ ]:
A = np.arange(1,7).reshape(2,3)
B = np.arange(7,13).reshape(3,2)
print(A)
print(B)
print("")

result_at = A @ B
print(result_at)
print("")


result_matmul = np.matmul(A,B)
print(result_at)
print("")

result_dot=np.dot(A,B)
print(result_dot)
print("")


#***note***
# "matmul" and "dot" have different behavour
# "dot"=> inner product (scalar)
# "matmul"=> matrix mutiplication

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]

[[ 58  64]
 [139 154]]

[[ 58  64]
 [139 154]]

[[ 58  64]
 [139 154]]



i dont know what is eigenvalue and eigenvector and i didnt understand by searching !!! :(

**the last one :**
determinant

In [ ]:
c = np.matmul(A,B)
print(A)
print("")
print(B)
print("")
print(c)
print("")

determinant = np.linalg.det(c)
print(determinant)

[[1 2 3]
 [4 5 6]]

[[ 7  8]
 [ 9 10]
 [11 12]]

[[ 58  64]
 [139 154]]

36.000000000000256
